### Get all tasks
GET http://localhost:3000/api/tasks

###

### Create task
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "HTTP Client task",
  "description": "Created from WebStorm",
  "priority": "medium",
  "status": "todo"
}

###

### Update task
PUT http://localhost:3000/api/tasks/de42da14-c05b-48b7-b2be-f1dedf1bfa89
Content-Type: application/json

{
  "title": "Updated PostgreSQL task",
  "description": "Task was updated successfully",
  "priority": "medium",
  "status": "in-progress"
}

###
DELETE http://localhost:3000/api/tasks/de42da14-c05b-48b7-b2be-f1dedf1bfa89